export default defineEventHandler(async () => {
  const data = [
    {
      id: 0,
      name: 'Company UX Guide',
      icon: '/img/icons/files/pdf.svg',
      size: '4.7MB',
      version: '1.5.2',
      uploaded: '2 weeks ago',
      author: {
        name: 'Hermann M.',
        picture: '/img/avatars/16.jpg',
      },
    },
    {
      id: 1,
      name: 'Thech summit expenses',
      icon: '/img/icons/files/sheet.svg',
      size: '34KB',
      version: '1.1.3',
      uploaded: '3 days ago',
      author: {
        name: 'Megan C.',
        picture: '/img/avatars/5.jpg',
      },
    },
    {
      id: 2,
      name: 'Project outline',
      icon: '/img/icons/files/doc-2.svg',
      size: '77KB',
      version: '1.0.0',
      uploaded: '5 days ago',
      author: {
        name: 'Megan C.',
        picture: '/img/avatars/5.jpg',
      },
    },
    {
      id: 3,
      name: 'UX presentation',
      icon: '/img/icons/files/ppt.svg',
      size: '2.3MB',
      version: '1.0.0',
      uploaded: '2 weeks ago',
      author: {
        name: 'Megan C.',
        picture: '/img/avatars/5.jpg',
      },
    },
    {
      id: 4,
      name: 'Website Homepage Redesign',
      icon: '/img/icons/files/ai.svg',
      size: '4.8MB',
      version: '1.0.0',
      uploaded: '2 weeks ago',
      author: {
        name: 'Megan C.',
        picture: '/img/avatars/5.jpg',
      },
    },
    {
      id: 5,
      name: 'UX Ramp Up for Interns',
      icon: '/img/icons/files/doc-2.svg',
      size: '1.8MB',
      version: '1.2.0',
      uploaded: '3 days ago',
      author: {
        name: 'Megan C.',
        picture: '/img/avatars/5.jpg',
      },
    },
    {
      id: 6,
      name: '2020 Projects Digest',
      icon: '/img/icons/files/pdf.svg',
      size: '8.9MB',
      version: '1.3.4',
      uploaded: '3 weeks ago',
      author: {
        name: 'Megan C.',
        picture: '/img/avatars/5.jpg',
      },
    },
    {
      id: 7,
      name: 'Financial Report - 2022',
      icon: '/img/icons/files/doc-2.svg',
      size: '1.2MB',
      version: '1.0.4',
      uploaded: '5 days ago',
      author: {
        name: 'Megan C.',
        picture: '/img/avatars/5.jpg',
      },
    },
    {
      id: 8,
      name: '2020 Supplier Expenses',
      icon: '/img/icons/files/doc-2.svg',
      size: '250KB',
      version: '1.0.0',
      uploaded: '6 days ago',
      author: {
        name: 'Megan C.',
        picture: '/img/avatars/5.jpg',
      },
    },
    {
      id: 9,
      name: 'Website About Page Redesign',
      icon: '/img/icons/files/ai.svg',
      size: '3.9MB',
      version: '1.2.4',
      uploaded: '4 days ago',
      author: {
        name: 'Megan C.',
        picture: '/img/avatars/5.jpg',
      },
    },
    {
      id: 10,
      name: 'Website Pricing Page Redesign',
      icon: '/img/icons/files/ai.svg',
      size: '2.6MB',
      version: '1.2.1',
      uploaded: '3 days ago',
      author: {
        name: 'Megan C.',
        picture: '/img/avatars/5.jpg',
      },
    },
    {
      id: 11,
      name: 'Financial Report - 2021',
      icon: '/img/icons/files/doc-2.svg',
      size: '1.6MB',
      version: '1.7.2',
      uploaded: '1 year ago',
      author: {
        name: 'Megan C.',
        picture: '/img/avatars/5.jpg',
      },
    },
    {
      id: 12,
      name: '2022 Supplier Expenses',
      icon: '/img/icons/files/doc-2.svg',
      size: '250KB',
      version: '1.0.0',
      uploaded: '6 days ago',
      author: {
        name: 'Megan C.',
        picture: '/img/avatars/5.jpg',
      },
    },
    {
      id: 13,
      name: '	Website Contact Page Redesign',
      icon: '/img/icons/files/ai.svg',
      size: '3.8',
      version: '1.1.5',
      uploaded: '8 days ago',
      author: {
        name: 'Megan C.',
        picture: '/img/avatars/5.jpg',
      },
    },
    {
      id: 14,
      name: 'Company Brand Book',
      icon: '/img/icons/files/pdf.svg',
      size: '7.9MB',
      version: '2.5.1',
      uploaded: '3 weeks ago',
      author: {
        name: 'Megan C.',
        picture: '/img/avatars/5.jpg',
      },
    },
    {
      id: 15,
      name: '2021 Projects Digest',
      icon: '/img/icons/files/pdf.svg',
      size: '5.9',
      version: '3.4.8',
      uploaded: '1 year ago',
      author: {
        name: 'Megan C.',
        picture: '/img/avatars/5.jpg',
      },
    },
    {
      id: 16,
      name: 'Landing page redesign',
      icon: '/img/icons/files/ai.svg',
      size: '1.8MB',
      version: '1.0.0',
      uploaded: '3 days ago',
      author: {
        name: 'Megan C.',
        picture: '/img/avatars/5.jpg',
      },
    },
    {
      id: 17,
      name: 'Budget reporting',
      icon: '/img/icons/files/sheet.svg',
      size: '34KB',
      version: '1.0.0',
      uploaded: '5 days ago',
      author: {
        name: 'Megan C.',
        picture: '/img/avatars/5.jpg',
      },
    },
    {
      id: 18,
      name: '2023 startegy report',
      icon: '/img/icons/files/pdf.svg',
      size: '4.3MB',
      version: '1.1.0',
      uploaded: '9 days ago',
      author: {
        name: 'Megan C.',
        picture: '/img/avatars/5.jpg',
      },
    },
    {
      id: 19,
      name: 'Investors presentation',
      icon: '/img/icons/files/ppt.svg',
      size: '34KB',
      version: '1.1.5',
      uploaded: '4 days ago',
      author: {
        name: 'Megan C.',
        picture: '/img/avatars/5.jpg',
      },
    },
  ]

  return data
})
