export default defineEventHandler(async () => {
  const data = [
    {
      id: 0,
      name: 'Introduction to Html5',
      picture: '/img/photos/courses/1.jpg',
      category: 'Web Development',
      difficulty: 1,
      price: 26,
      skill: {
        icon: 'lnil lnil-html5',
        name: 'Html5',
      },
      author: {
        id: 8,
        picture: '/images/avatars/svg/vuero-1.svg',
        username: 'Erik K.',
        initials: 'EK',
        color: 'info',
      },
    },
    {
      id: 1,
      name: 'Mastering VueJS and Typescript',
      picture: '/img/photos/courses/2.png',
      category: 'Web Development',
      difficulty: 4,
      price: 12,
      skill: {
        icon: 'lnir lnir-nodejs',
        name: 'NodeJS',
      },
      author: {
        id: 12,
        picture: '/img/avatars/12.jpg',
        username: 'Joshua S.',
        initials: 'JS',
        color: 'info',
      },
    },
    {
      id: 2,
      name: 'Discovering CSS3 and Stylesheets',
      picture: '/img/photos/courses/3.jpg',
      category: 'Web Development',
      difficulty: 2,
      price: 16,
      skill: {
        icon: 'lnir lnir-css3',
        name: 'CSS3',
      },
      author: {
        id: 12,
        picture: '/img/avatars/5.jpg',
        username: 'Mary L.',
        initials: 'ML',
        color: 'info',
      },
    },
    {
      id: 3,
      name: 'Get Started with Laravel 6',
      picture: '/img/photos/courses/4.png',
      category: 'Web Development',
      difficulty: 3,
      price: 0,
      skill: {
        icon: 'lnir lnir-laravel',
        name: 'Laravel',
      },
      author: {
        id: 18,
        picture: '/img/avatars/18.jpg',
        username: 'Esteban C.',
        initials: 'EC',
        color: 'info',
      },
    },
    {
      id: 4,
      name: 'Python Basics for Beginners',
      picture: '/img/photos/courses/5.jpeg',
      category: 'Web Development',
      difficulty: 1,
      price: 8,
      skill: {
        icon: 'lnir lnir-python',
        name: 'Python',
      },
      author: {
        id: 18,
        picture: '/img/avatars/18.jpg',
        username: 'Esteban C.',
        initials: 'EC',
        color: 'info',
      },
    },
    {
      id: 5,
      name: 'Mastering State with React Hooks',
      picture: '/img/photos/courses/6.jpg',
      category: 'Web Development',
      difficulty: 4,
      price: 25,
      skill: {
        icon: 'lnir lnir-react',
        name: 'ReactJS',
      },
      author: {
        id: 30,
        picture: '/img/avatars/30.jpg',
        username: 'Clément D.',
        initials: 'CD',
        color: 'info',
      },
    },
    {
      id: 6,
      name: 'Setting up an Express Server',
      picture: '/img/photos/courses/7.png',
      category: 'Web Development',
      difficulty: 3,
      price: 12,
      skill: {
        icon: 'lnir lnir-nodejs',
        name: 'NodeJS',
      },
      author: {
        id: 38,
        picture: '/img/avatars/38.jpg',
        username: 'Christie D.',
        initials: 'CD',
        color: 'info',
      },
    },
    {
      id: 7,
      name: 'Learning to use Kubernetes',
      picture: '/img/photos/courses/9.jpg',
      category: 'Web Development',
      difficulty: 5,
      price: 34,
      skill: {
        icon: 'lnir lnir-chrome',
        name: 'Kubernetes',
      },
      author: {
        id: 30,
        picture: '/img/avatars/30.jpg',
        username: 'Clément D.',
        initials: 'CD',
        color: 'info',
      },
    },
    {
      id: 8,
      name: 'Another Angular Crash Course',
      picture: '/img/photos/courses/11.jpg',
      category: 'Web Development',
      difficulty: 4,
      price: 22,
      skill: {
        icon: 'lnir lnir-angular',
        name: 'Angular',
      },
      author: {
        id: 34,
        picture: '/img/avatars/34.jpg',
        username: 'Daniel R.',
        initials: 'DR',
        color: 'info',
      },
    },
    {
      id: 9,
      name: 'learning Advanced Docker Concepts',
      picture: '/img/photos/courses/12.jpg',
      category: 'Web Development',
      difficulty: 5,
      price: 35,
      skill: {
        icon: 'lnir lnir-docker',
        name: 'Docker',
      },
      author: {
        id: 30,
        picture: '/img/avatars/30.jpg',
        username: 'Clément D.',
        initials: 'CD',
        color: 'info',
      },
    },
  ]

  return data
})
