export default defineEventHandler(async () => {
  const data = [
    {
      id: '1',
      name: 'Delivery App Project',
      dueDate: 'August 2020',
      updated: '3m ago',
      image: '/img/apps/1.jpg',
      owner: {
        id: 7,
        avatar: '/img/avatars/7.svg',
        name: 'Alice C.',
        initials: 'AC',
        color: 'info',
      },
      team: [
        {
          id: 27,
          picture: '/img/avatars/27.svg',
          name: 'Carmen E.',
          initials: 'CE',
          color: 'h-yellow',
        },
        {
          id: 15,
          picture: '/img/avatars/15.svg',
          name: 'Hilde V.',
          initials: 'HV',
          color: 'h-purple',
        },
        {
          id: 12,
          picture: '/img/avatars/12.svg',
          name: 'Joshua S.',
          initials: 'JS',
          color: 'success',
        },
      ],
    },
    {
      id: '2',
      name: 'Health and Fitness Dashboard',
      dueDate: 'October 2020',
      updated: '5h ago',
      image: '/img/apps/2.png',
      owner: {
        id: 8,
        avatar: '/img/avatars/12.svg',
        name: 'Erik K.',
        initials: 'EK',
        color: 'info',
      },
      team: [
        {
          id: 13,
          picture: '/img/avatars/13.svg',
          name: 'Tara S.',
          initials: 'TS',
          color: 'danger',
        },
        {
          id: 21,
          picture: '/img/avatars/21.svg',
          name: 'Elizabet F.',
          initials: 'EF',
          color: 'warning',
        },
      ],
    },
    {
      id: '3',
      name: 'Learning Tracker Dashboard',
      dueDate: 'September 2020',
      updated: '5h ago',
      image: '/img/apps/3.png',
      owner: {
        id: 25,
        avatar: '/img/avatars/25.svg',
        name: 'Melany W.',
        initials: 'MW',
        color: 'info',
      },
      team: [
        {
          id: 14,
          picture: '/img/avatars/14.svg',
          name: 'Ryan B.',
          initials: 'RB',
          color: 'info',
        },
      ],
    },
    {
      id: '4',
      name: 'Banking and Finance Dashboard',
      dueDate: 'October 2020',
      updated: '5h ago',
      image: '/img/apps/4.png',
      owner: {
        id: 23,
        avatar: '/img/avatars/23.svg',
        name: 'Irina V.',
        initials: 'IV',
        color: 'success',
      },
      team: [
        {
          id: 13,
          picture: '/img/avatars/13.svg',
          name: 'Tara S.',
          initials: 'TS',
          color: 'danger',
        },
        {
          id: 21,
          picture: '/img/avatars/21.svg',
          name: 'Elizabet F.',
          initials: 'EF',
          color: 'warning',
        },
      ],
    },
    {
      id: '5',
      name: 'Resume Management Mobile App',
      dueDate: 'October 2020',
      updated: '2h ago',
      image: '/img/apps/5.png',
      owner: {
        id: 11,
        avatar: '/img/avatars/11.svg',
        name: 'Kelly M.',
        initials: 'KM',
        color: 'h-orange',
      },
      team: [
        {
          id: 30,
          picture: '/img/avatars/30.svg',
          name: 'Clément D.',
          initials: 'CD',
          color: 'info',
        },
        {
          id: 39,
          picture: '/img/avatars/39.svg',
          name: 'Alejandro B.',
          initials: 'AB',
          color: 'h-purple',
        },
      ],
    },
    {
      id: '6',
      name: 'Banking Landing Page',
      dueDate: 'December 2020',
      updated: '3d ago',
      image: '/img/apps/6.png',
      owner: {
        id: 9,
        avatar: '/img/avatars/9.svg',
        name: 'Ana B.',
        initials: 'AB',
        color: 'success',
      },
      team: [
        {
          id: 15,
          picture: '/img/avatars/15.svg',
          name: 'Hilde V.',
          initials: 'HV',
          color: 'info',
        },
        {
          id: 40,
          picture: '/img/avatars/40.svg',
          name: 'Jeanne M.',
          initials: 'JM',
          color: 'success',
        },
        {
          id: 8,
          picture: '/img/avatars/11.svg',
          name: 'Erik K.',
          initials: 'EK',
          color: 'h-purple',
        },
      ],
    },
    {
      id: '7',
      name: 'Learning App Design',
      dueDate: 'November 2020',
      updated: '1h ago',
      image: '/img/apps/7.png',
      owner: {
        id: 25,
        avatar: '/img/avatars/25.svg',
        name: 'Melany W.',
        initials: 'MW',
        color: 'info',
      },
      team: [
        {
          id: 11,
          picture: '/img/avatars/11.svg',
          name: 'Kelly M.',
          initials: 'KM',
          color: 'success',
        },
      ],
    },
    {
      id: '8',
      name: 'Educational App Design',
      dueDate: 'November 2020',
      updated: '4d ago',
      image: '/img/apps/8.png',
      owner: {
        id: 5,
        avatar: '/img/avatars/5.svg',
        name: 'Mary L.',
        initials: 'ML',
        color: 'info',
      },
      team: [
        {
          id: 21,
          picture: '/img/avatars/21.svg',
          name: 'Elizabeth F.',
          initials: 'EF',
          color: 'warning',
        },
        {
          id: 29,
          picture: '/img/avatars/29.svg',
          name: 'Hakeem C.',
          initials: 'HC',
          color: 'danger',
        },
        {
          id: 33,
          picture: '/img/avatars/33.svg',
          name: 'Harvey M.',
          initials: 'HM',
          color: 'success',
        },
      ],
    },
    {
      id: '9',
      name: 'Banking Solution Website',
      dueDate: 'October 2020',
      updated: '2h ago',
      image: '/img/apps/9.png',
      owner: {
        id: 27,
        avatar: '/img/avatars/27.svg',
        name: 'Carmen E.',
        initials: 'CE',
        color: 'info',
      },
      team: [
        {
          id: 30,
          picture: '/img/avatars/30.svg',
          name: 'Clément D.',
          initials: 'CD',
          color: 'h-purple',
        },
        {
          id: 19,
          picture: '/img/avatars/19.svg',
          name: 'Greta K.',
          initials: 'GK',
          color: 'info',
        },
      ],
    },
    {
      id: '10',
      name: 'HR Webapp Design',
      dueDate: 'August 2020',
      updated: '2h ago',
      image: '/img/apps/10.png',
      owner: {
        id: 27,
        avatar: '/img/avatars/27.svg',
        name: 'Carmen E.',
        initials: 'CE',
        color: 'info',
      },
      team: [
        {
          id: 24,
          picture: '/img/avatars/24.svg',
          name: 'Sandrine C.',
          initials: 'SC',
          color: 'success',
        },
        {
          id: 22,
          picture: '/img/avatars/22.svg',
          name: 'Jimmy H.',
          initials: 'JH',
          color: 'info',
        },
      ],
    },
    {
      id: '11',
      name: 'Ice Cream Delivery Dashboard',
      dueDate: 'January 2021',
      updated: '2h ago',
      image: '/img/apps/11.png',
      owner: {
        id: 13,
        avatar: '/img/avatars/13.svg',
        name: 'Tara S.',
        initials: 'TS',
        color: 'danger',
      },
      team: [
        {
          id: 28,
          picture: '/img/avatars/28.svg',
          name: 'Edouard F.',
          initials: 'EF',
          color: 'info',
        },
      ],
    },
    {
      id: '12',
      name: 'Mobile App Landing Page',
      dueDate: 'November 2020',
      updated: '4d ago',
      image: '/img/apps/12.jpg',
      owner: {
        id: 12,
        avatar: '/img/avatars/12.svg',
        name: 'Joshua S.',
        initials: 'JS',
        color: 'info',
      },
      team: [
        {
          id: 119,
          picture: undefined,
          name: 'Sarah Connor.',
          initials: 'SC',
          color: 'h-purple',
        },
      ],
    },
    {
      id: '13',
      name: 'Web Marketing Landing Page',
      dueDate: 'November 2020',
      updated: '3m ago',
      image: '/img/apps/13.png',
      owner: {
        id: 12,
        avatar: '/img/avatars/12.svg',
        name: 'Joshua S.',
        initials: 'JS',
        color: 'info',
      },
      team: [
        {
          id: 8,
          picture: '/img/avatars/13.svg',
          name: 'Erik K.',
          initials: 'EK',
          color: 'h-purple',
        },
        {
          id: 15,
          picture: '/img/avatars/15.svg',
          name: 'Hilde V.',
          initials: 'HV',
          color: 'h-orange',
        },
        {
          id: 12,
          picture: '/img/avatars/40.svg',
          name: 'Jeanne M.',
          initials: 'JM',
          color: 'success',
        },
      ],
    },
    {
      id: '14',
      name: 'Startup Landing Page',
      dueDate: 'November 2020',
      updated: '3m ago',
      image: '/img/apps/14.jpg',
      owner: {
        id: 15,
        avatar: '/img/avatars/15.svg',
        name: 'Hilde V.',
        initials: 'HV',
        color: 'danger',
      },
      team: [
        {
          id: 31,
          picture: '/img/avatars/31.svg',
          name: 'Yasseen A.',
          initials: 'YA',
          color: 'info',
        },
      ],
    },
    {
      id: '15',
      name: 'Expense Management System',
      dueDate: 'January 2021',
      updated: '2d ago',
      image: '/img/apps/15.png',
      owner: {
        id: 39,
        avatar: '/img/avatars/39.svg',
        name: 'Alejandro B.',
        initials: 'AB',
        color: 'info',
      },
      team: [
        {
          id: 5,
          picture: '/img/avatars/5.svg',
          name: 'Mary L.',
          initials: 'ML',
          color: 'info',
        },
        {
          id: 24,
          picture: '/img/avatars/24.svg',
          name: 'Sandrine C.',
          initials: 'SC',
          color: 'success',
        },
      ],
    },
  ]

  return data
})
