<script setup lang="ts">
const demoTwo = ref(true)
</script>

<template>
  <BaseCheckbox
    v-model="demoTwo"
    name="demo-rounded-1"
    label="Default"
    shape="rounded"
  />
  <BaseCheckbox
    v-model="demoTwo"
    name="demo-rounded-2"
    label="Muted"
    shape="rounded"
    color="muted"
  />
  <BaseCheckbox
    v-model="demoTwo"
    name="demo-rounded-3"
    label="Primary"
    shape="rounded"
    color="primary"
  />
  <BaseCheckbox
    v-model="demoTwo"
    name="demo-rounded-4"
    label="Info"
    shape="rounded"
    color="info"
  />
  <BaseCheckbox
    v-model="demoTwo"
    name="demo-rounded-5"
    label="Success"
    shape="rounded"
    color="success"
  />
  <BaseCheckbox
    v-model="demoTwo"
    name="demo-rounded-6"
    label="Warning"
    shape="rounded"
    color="warning"
  />
  <BaseCheckbox
    v-model="demoTwo"
    name="demo-rounded-2"
    label="Danger"
    shape="rounded"
    color="danger"
  />
</template>
