<script setup lang="ts">
const demoOne = ref(true)
</script>

<template>
  <BaseCheckbox
    v-model="demoOne"
    name="demo-straight-1"
    label="Default"
    shape="straight"
  />
  <BaseCheckbox
    v-model="demoOne"
    name="demo-straight-2"
    label="Muted"
    shape="straight"
    color="muted"
  />
  <BaseCheckbox
    v-model="demoOne"
    name="demo-straight-3"
    label="Primary"
    shape="straight"
    color="primary"
  />
  <BaseCheckbox
    v-model="demoOne"
    name="demo-straight-4"
    label="Info"
    shape="straight"
    color="info"
  />
  <BaseCheckbox
    v-model="demoOne"
    name="demo-straight-5"
    label="Success"
    shape="straight"
    color="success"
  />
  <BaseCheckbox
    v-model="demoOne"
    name="demo-straight-6"
    label="Warning"
    shape="straight"
    color="warning"
  />
  <BaseCheckbox
    v-model="demoOne"
    name="demo-straight-2"
    label="Danger"
    shape="straight"
    color="danger"
  />
</template>
