export const properties = {
  props: [
    {
      name: 'modelValue',
      type: 'any',
      required: 'true',
      default: 'undefined',
      values: ['any'],
    },
    {
      name: 'name',
      type: 'string',
      required: 'false',
      default: 'text',
      values: ['string'],
    },
    {
      name: 'shape',
      type: 'string',
      required: 'false',
      default: 'text',
      values: ['straight', 'rounded', 'curved'],
    },
    {
      name: 'label',
      type: 'string',
      required: 'true',
      default: 'undefined',
      values: ['string'],
    },
    {
      name: 'hideLabel',
      type: 'boolean',
      required: 'false',
      default: 'false',
      values: ['boolean'],
    },
    {
      name: 'colorFocus',
      type: 'boolean',
      required: 'false',
      default: 'false',
      values: ['boolean'],
    },
    {
      name: 'placeholder',
      type: 'string',
      required: 'false',
      default: '',
      values: ['string'],
    },
    {
      name: 'icon',
      type: 'string',
      required: 'false',
      default: 'undefined',
      values: ['string'],
    },
    {
      name: 'loading',
      type: 'boolean',
      required: 'false',
      default: 'false',
      values: ['boolean'],
    },
    {
      name: 'disabled',
      type: 'boolean',
      required: 'false',
      default: 'false',
      values: ['boolean'],
    },
    {
      name: 'readonly',
      type: 'boolean',
      required: 'false',
      default: 'false',
      values: ['boolean'],
    },
    {
      name: 'invalid',
      type: 'boolean',
      required: 'false',
      default: 'false',
      values: ['boolean'],
    },
    {
      name: 'addon',
      type: 'boolean',
      required: 'false',
      default: 'false',
      values: ['boolean'],
    },
    {
      name: 'resize',
      type: 'boolean',
      required: 'false',
      default: 'false',
      values: ['boolean'],
    },
    {
      name: 'errorText',
      type: 'string',
      required: 'false',
      default: '',
      values: ['string'],
    },
    {
      name: 'rows',
      type: 'number',
      required: 'false',
      default: '4',
      values: ['string'],
    },
  ],
  slots: [
    {
      name: '#addon',
      properties: ['null'],
      description: 'Holds the textarea addon content',
    },
  ],
}
