<template>
  <BaseSwitchBall
    id="demo-ball-1"
    :checked="true"
    label="Primary"
    color="primary"
  />
  <BaseSwitchBall
    id="demo-ball-2"
    :checked="true"
    label="Info"
    color="info"
  />
  <BaseSwitchBall
    id="demo-ball-3"
    :checked="true"
    label="Success"
    color="success"
  />
  <BaseSwitchBall
    id="demo-ball-4"
    :checked="true"
    label="Warning"
    color="warning"
  />
  <BaseSwitchBall
    id="demo-ball-5"
    :checked="true"
    label="Danger"
    color="danger"
  />
</template>
