export const properties = {
  props: [
    {
      name: 'modelValue',
      type: 'any',
      required: 'false',
      default: 'undefined',
      values: ['any'],
    },
    {
      name: 'items',
      type: 'AutocompleteItem[ ]',
      required: 'true',
      default: '() => [ ]',
      values: ['Array'],
    },
    {
      name: 'shape',
      type: 'AutocompleteShapes',
      required: 'false',
      default: 'rounded',
      values: ['straight', 'rounded', 'curved', 'full'],
    },
    {
      name: 'label',
      type: 'string',
      required: 'true',
      default: 'undefined',
      values: ['string'],
    },
    {
      name: 'hideLabel',
      type: 'boolean',
      required: 'false',
      default: 'false',
      values: ['boolean'],
    },
    {
      name: 'icon',
      type: 'string',
      required: 'false',
      default: 'undefined',
      values: ['string'],
    },
    {
      name: 'placeholder',
      type: 'string',
      required: 'false',
      default: '',
      values: ['string'],
    },
    {
      name: 'clearable',
      type: 'boolean',
      required: 'false',
      default: 'false',
      values: ['boolean'],
    },
    {
      name: 'multiple',
      type: 'boolean',
      required: 'false',
      default: 'false',
      values: ['boolean'],
    },
    {
      name: 'loading',
      type: 'boolean',
      required: 'false',
      default: 'false',
      values: ['boolean'],
    },
    {
      name: 'disabled',
      type: 'boolean',
      required: 'false',
      default: 'false',
      values: ['boolean'],
    },
  ],
  slots: [],
}
