export default defineEventHandler(async () => {
  const data = [
    {
      id: 0,
      username: 'Erik K.',
      position: 'Product Manager',
      picture: '/images/avatars/20.svg',
      badge: '/images/icons/flags/united-states-of-america.svg',
      location: 'Las Vegas, NV',
      industry: 'Software',
      status: 'Online',
      relations: [
        {
          id: 0,
          picture: '/img/avatars/25.svg',
          initials: 'AC',
          color: 'info',
        },
        {
          id: 1,
          picture: undefined,
          initials: 'JP',
          color: 'info',
        },
        {
          id: 2,
          picture: '/images/avatars/11.svg',
          initials: 'EK',
          color: 'h-purple',
        },
        {
          id: 3,
          picture: '/img/avatars/5.svg',
          initials: 'ML',
          color: 'danger',
        },
        {
          id: 4,
          picture: undefined,
          initials: 'SC',
          color: 'success',
        },
      ],
    },
    {
      id: 1,
      username: 'Jimmy H.',
      position: 'Project Manager',
      picture: '/img/avatars/22.svg',
      badge: '/images/icons/flags/united-states-of-america.svg',
      location: 'Los Angeles, CA',
      industry: 'Business',
      status: 'Working',
      relations: [
        {
          id: 148,
          picture: undefined,
          initials: 'SC',
          color: 'h-purple',
        },
      ],
    },
    {
      id: 2,
      username: 'Melany W.',
      position: 'Web Developer',
      picture: '/img/avatars/25.svg',
      badge: '/images/icons/flags/united-states-of-america.svg',
      location: 'San Jose, CA',
      industry: 'Design',
      status: 'Online',
      relations: [
        {
          id: 127,
          picture: undefined,
          initials: 'BT',
          color: 'success',
        },
        {
          id: 7,
          picture: '/img/avatars/7.svg',
          initials: 'AC',
          color: 'h-purple',
        },
        {
          id: 19,
          picture: '/img/avatars/19.svg',
          initials: 'GK',
          color: 'h-yellow',
        },
        {
          id: 148,
          picture: undefined,
          initials: 'SC',
          color: 'h-purple',
        },
        {
          id: 149,
          picture: undefined,
          initials: 'SC',
          color: 'h-purple',
        },
        {
          id: 150,
          picture: undefined,
          initials: 'SC',
          color: 'h-purple',
        },
      ],
    },
    {
      id: 3,
      username: 'Joshua S.',
      position: 'Backend Developer',
      picture: '/img/avatars/12.svg',
      badge: '/images/icons/flags/united-states-of-america.svg',
      location: 'Las Vegas, NV',
      industry: 'Accounting',
      status: 'Suspended',
      relations: [
        {
          id: 7,
          picture: '/img/avatars/13.svg',
          initials: 'TS',
          color: 'info',
        },
      ],
    },
    {
      id: 4,
      username: 'Tara S.',
      position: 'UI/UX Designer',
      picture: '/img/avatars/13.svg',
      badge: '/images/icons/flags/united-states-of-america.svg',
      location: 'Los Angeles, CA',
      industry: 'Finance',
      status: 'Working',
      relations: [
        {
          id: 0,
          picture: '/img/avatars/25.svg',
          initials: 'AC',
          color: 'info',
        },
        {
          id: 14,
          picture: '/img/avatars/11.svg',
          initials: 'KL',
          color: 'danger',
        },
        {
          id: 17,
          picture: '/img/avatars/5.svg',
          initials: 'ML',
          color: 'warning',
        },
        {
          id: 150,
          picture: undefined,
          initials: 'SC',
          color: 'h-purple',
        },
        {
          id: 151,
          picture: undefined,
          initials: 'SC',
          color: 'h-purple',
        },
        {
          id: 152,
          picture: undefined,
          initials: 'SC',
          color: 'h-purple',
        },
        {
          id: 154,
          picture: undefined,
          initials: 'SC',
          color: 'h-purple',
        },
      ],
    },
    {
      id: 5,
      username: 'Greta K.',
      position: 'Sales Manager',
      picture: '/img/avatars/19.svg',
      badge: '/images/icons/flags/germany.svg',
      location: 'Berlin, Germany',
      industry: 'Business',
      status: 'Online',
      relations: [
        {
          id: 0,
          picture: '/img/avatars/25.svg',
          initials: 'AC',
          color: 'info',
        },
        {
          id: 14,
          picture: undefined,
          initials: 'AT',
          color: 'h-yellow',
        },
        {
          id: 17,
          picture: '/img/avatars/5.svg',
          initials: 'ML',
          color: 'warning',
        },
        {
          id: 150,
          picture: undefined,
          initials: 'SC',
          color: 'h-purple',
        },
        {
          id: 151,
          picture: undefined,
          initials: 'SC',
          color: 'h-purple',
        },
        {
          id: 152,
          picture: undefined,
          initials: 'SC',
          color: 'h-purple',
        },
      ],
    },
    {
      id: 6,
      username: 'Clément D.',
      position: 'Software Engineer',
      picture: '/img/avatars/30.svg',
      badge: '/images/icons/flags/france.svg',
      location: 'Toulouse, France',
      industry: 'Software',
      status: 'Offline',
      relations: [
        {
          id: 0,
          picture: '/img/avatars/25.svg',
          initials: 'AC',
          color: 'info',
        },
        {
          id: 14,
          picture: undefined,
          initials: 'BV',
          color: 'h-purple',
        },
        {
          id: 8,
          picture: '/images/avatars/16.svg',
          initials: 'ML',
          color: 'warning',
        },
        {
          id: 150,
          picture: undefined,
          initials: 'SC',
          color: 'h-purple',
        },
        {
          id: 151,
          picture: undefined,
          initials: 'SC',
          color: 'h-purple',
        },
      ],
    },
    {
      id: 7,
      username: 'Kelly M.',
      position: 'Product Manager',
      picture: '/img/avatars/11.svg',
      badge: '/images/icons/flags/england.svg',
      location: 'London, UK',
      industry: 'Software',
      status: 'Online',
      relations: [
        {
          id: 25,
          picture: '/img/avatars/25.svg',
          initials: 'AC',
          color: 'info',
        },
        {
          id: 13,
          picture: '/img/avatars/13.svg',
          initials: 'TS',
          color: 'info',
        },
        {
          id: 17,
          picture: '/img/avatars/5.svg',
          initials: 'ML',
          color: 'warning',
        },
      ],
    },
    {
      id: 8,
      username: 'Alan T.',
      position: 'Software Engineer',
      picture: undefined,
      badge: '/images/icons/flags/united-states-of-america.svg',
      color: 'h-yellow',
      initials: 'AT',
      location: 'San Francisco, CA',
      industry: 'Software',
      status: 'Offline',
      relations: [
        {
          id: 25,
          picture: '/img/avatars/25.svg',
          initials: 'MW',
          color: 'info',
        },
      ],
    },
    {
      id: 9,
      username: 'Courtney W.',
      position: 'Web Developer',
      picture: '/img/avatars/26.svg',
      badge: '/images/icons/flags/australia.svg',
      location: 'Melbourne, Australia',
      industry: 'Software',
      status: 'Offline',
      relations: [
        {
          id: 7,
          picture: '/img/avatars/7.svg',
          initials: 'AC',
          color: 'info',
        },
        {
          id: 165,
          picture: undefined,
          initials: 'JD',
          color: 'info',
        },
        {
          id: 27,
          picture: '/img/avatars/27.svg',
          initials: 'CE',
          color: 'warning',
        },
        {
          id: 150,
          picture: undefined,
          initials: 'SC',
          color: 'h-purple',
        },
        {
          id: 151,
          picture: undefined,
          initials: 'SC',
          color: 'h-purple',
        },
      ],
    },
  ]

  return data
})
